# Generated by Django 3.2.9 on 2021-11-21 19:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created', '-updated'], 'verbose_name': 'Yorum', 'verbose_name_plural': 'Yorumlar'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='uptated',
            new_name='updated',
        ),
    ]
